<a href="https://colab.research.google.com/github/z-arabi/pytorchTutorial/blob/master/02_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

In [3]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([-6.0086e+19])
tensor([-6.0087e+19,  3.0613e-41,  5.0447e-44])
tensor([[-6.0087e+19,  3.0613e-41,  5.0447e-44],
        [ 0.0000e+00,         nan,  3.0613e-41]])
tensor([[[-6.0087e+19,  3.0613e-41,  5.0447e-44],
         [ 0.0000e+00,         nan,  3.0613e-41]],

        [[ 1.3788e-14,  3.6423e-06,  2.0699e-19],
         [ 3.3738e-12,  7.4086e+28,  6.9397e+22]]])


In [4]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.2530, 0.4093, 0.6680],
        [0.1465, 0.1946, 0.5402],
        [0.1133, 0.8879, 0.4688],
        [0.7251, 0.4483, 0.0784],
        [0.5737, 0.5724, 0.3480]])


In [5]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# check size
print(x.size())

torch.Size([5, 3])


In [7]:
# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [8]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [9]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [10]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print("x is ",x)
print("y is ",y)

# elementwise addition
z1 = x + y
print(z1)

z2 = torch.add(x,y)
print(z2)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y2 = y
print(y2)
y2.add_(x)
print(y2)

x is  tensor([[0.9553, 0.4526],
        [0.2520, 0.6369]])
y is  tensor([[0.6576, 0.0884],
        [0.2052, 0.8267]])
tensor([[1.6129, 0.5410],
        [0.4571, 1.4636]])
tensor([[1.6129, 0.5410],
        [0.4571, 1.4636]])
tensor([[0.6576, 0.0884],
        [0.2052, 0.8267]])
tensor([[1.6129, 0.5410],
        [0.4571, 1.4636]])


In [11]:
# substraction
z = x - y
z = torch.sub(x, y)
z

tensor([[-0.6576, -0.0884],
        [-0.2052, -0.8267]])

In [12]:
# multiplication
z = x * y
z = torch.mul(x,y)
z

tensor([[1.5409, 0.2448],
        [0.1152, 0.9322]])

In [13]:
# division
z = x / y
z = torch.div(x,y)
z

tensor([[0.5923, 0.8366],
        [0.5512, 0.4352]])

In [14]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.8292, 0.7949, 0.2661],
        [0.3183, 0.7260, 0.8025],
        [0.8025, 0.9500, 0.6653],
        [0.8209, 0.6538, 0.1918],
        [0.4853, 0.9717, 0.9662]])
tensor([0.8292, 0.3183, 0.8025, 0.8209, 0.4853])
tensor([0.3183, 0.7260, 0.8025])
tensor(0.7260)


In [15]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.7260116934776306


In [16]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
print(torch.cuda.is_available())
print(torch.device("cuda"))

True
cuda


In [29]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object

    x = torch.ones(5, device=device)  # directly create a tensor on GPU

    y = torch.ones(5)
    y = y.to(device)                       # or just use strings ``.to("cuda")``

    z = x + y # z is in GPU
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors

    # move to CPU again
    z = z.to("cpu")       # ``.to`` can also change dtype together!
    print(z.dtype)
    z = z.numpy()
    print(z.dtype)


torch.float32
float32
